Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -7,12 +7,11 @@ pipeline {
     }
     environment {
         DOCKER_HUB_REGISTRY = 'https://index.docker.io/v1/'
-        DOCKER_HUB_USERNAME = 'learnerharsh' // Replace with your Docker Hub username
-        DOCKER_IMAGE = "${DOCKER_HUB_USERNAME}/ultimate-cicd:${BUILD_NUMBER}"
+        DOCKER_HUB_USERNAME = 'learnerharsh'
+        DOCKER_IMAGE = "${DOCKER_HUB_USERNAME}/ultimate-cicd:latest"  // Specify the desired image tag or version
         SONAR_URL = "http://13.233.4.226:9000/"
         GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
         GIT_USER_NAME = "harsh-learner"
-        PLACEHOLDER = '##IMAGE_TAG##'
     }
     stages {
         stage('Checkout') {
@@ -36,17 +35,6 @@ pipeline {
                 }
             }
         }
-        stage('Build and Push Docker Image') {
-            steps {
-                script {
-                    sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
-                    def dockerImage = docker.image("${DOCKER_IMAGE}")
-                    docker.withRegistry("${DOCKER_HUB_REGISTRY}", "docker-cred") {
-                        dockerImage.push()
-                    }
-                }
-            }
-        }
         stage('Update Deployment File') {
             steps {
                 withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
@@ -54,15 +42,20 @@ pipeline {
                         git config user.email "harsh.xyz@gmail.com"
                         git config user.name "Harsh-Learner"
                         BUILD_NUMBER=${BUILD_NUMBER}
-                        if ! grep -q "${PLACEHOLDER}" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml; then
-                            echo "Adding ${PLACEHOLDER} placeholder to deployment.yml"
-                            echo "image: learnerharsh/ultimate-cicd:${PLACEHOLDER}" >> java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                        
+                        # Replace the image tag directly in the deployment.yml
+                        sed -i "s|image: learnerharsh/ultimate-cicd:${PLACEHOLDER}|image: ${DOCKER_IMAGE}|" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+
+                        # Check if the image tag is updated in the deployment.yml
+                        if grep -q "${DOCKER_IMAGE}" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml; then
+                            echo "Image tag updated successfully."
+                        else
+                            echo "Failed to update image tag in the deployment manifest."
+                            exit 1  # Exit the pipeline with an error status
                         fi
 
-                        sed -i "s/${PLACEHOLDER}/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                        git add -A  # Add all changes, including untracked files
-                        git status  # Print status to debug
-                        git commit -m "Commit all changes before updating deployment image to version ${BUILD_NUMBER}"
+                        git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
+                        git commit -m "Update deployment image to version ${DOCKER_IMAGE}"
                         git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                     '''
                 }
@@ -70,3 +63,4 @@ pipeline {
         }
     }
 }
+
